### ISSUE TITLE
`fill_value` in Mark 4, 5B stream reader `read` method doesn't do anything

### ISSUE THREAD

**Issue by cczhu** [mhvk/baseband#101]
I figure this is a result of a combination of function standardization and Mark 4 and 5B not having an invalid data flag, but don't like the fact the user can set an argument that doesn't actually do anything.  Should we at least mention in the docstring this currently doesn't function?

**Comment by mhvk** [comment]
Mark 4 and 5B can indicate invalid data, so that this is not used is a bug! (Both frame classes do have a `.valid` property.)
