### ISSUE TITLE
`fill_value` doesn't do anything for the first frame(set) using any stream reader

### ISSUE THREAD

**Issue by cczhu** [mhvk/baseband#106]
Following on #101: because `fill_value` is passed to a frame(set) reader, which sets invalid values with `fill_value`, and because the first frame is read upon initialization, `fill_value` in the stream readers' `read` method doesn't do anything until a new frame is read in.  Likewise if the user switches `fill_value` while reading, and the stream reader doesn't need to read in a new frame, the `fill_value` remains whatever the user previously set.

Solutions:
- Allow the user to pass `fill_value` upon stream reader initialization.  This doesn't solve the issue when switching `fill_value` in the middle of a frame, and feels clunky.
- Within `read`, check if `fill_value == self._frame(set).invalid_data_value`, and reread the frame(set) if it isn't.  This makes the `read` method more complicated, but is invisible to the user and shouldn't slow down `read` too much (since, if the user sticks to a convention, we've only added an if statement check).

Not a high priority issue - no one complained that `fill_value` didn't do anything in Mark4 and 5B, so it's likely not a feature people need.

**Comment by mhvk** [comment]
Are you sure that the first frame is an issue? On starting `read`, one could set `frame.invalid_data_value` and that would work fine.

**Comment by mhvk** [comment]
p.s. I do agree this is not a high-priority issue - 0. seems the only reasonable number (well, I guess `NaN` is not crazy either, or returning a `MaskedArray`).

**Comment by cczhu** [comment]
That's right, except that we cache the data within a VDIF frame set, and within the stream readers' `_frame_data`, so the user needs a way to set `frame.invalid_data_value` prior to decoding.  In Mark 4 and 5B, this was confusingly being done in `_read_frame` and again in `read` (which was "needed" because reading the first frame isn't done by `_read_frame`).  If we remove the one in `read`, then the issue remains.  I've thus kept it in `read`.  See #104.

**Comment by mhvk** [comment]
closing since will be fixed by #104
