### ISSUE TITLE
Reminder: more efficient Mark4 decoder

### ISSUE THREAD

**Issue by cczhu** [mhvk/baseband#108]
Reproducing Marten's comment in #104 regarding `baseband/mark4/base.py`, since we won't be implementing it in #104 itself:

> We can make the decoding somewhat less inefficient by using the fact that one can slice the frame, in which case only part will be decoded; so remove this one and rewrite as:

```
nsample = ...
selection = slice(sample_offset, sample_offset + nsample)
if self.thread_ids:
    selection = (selection, self.thread_ids)
sample = self.offset - offset0
result[sample:sample + nsample] = self._frame[selection]
```

**Comment by mhvk** [comment]
This should be possible for all formats, and perhaps is better done as part of moving `read()` up to VLBI base.

**Comment by cczhu** [comment]
#118 (inadvertently) resolves this issue, though the frame still can't be sliced for some reason.  Opened #128 to address that.
