### ISSUE TITLE
Methods for copying frames?

### ISSUE THREAD

**Issue by cczhu** [mhvk/baseband#126]
While there's a native copy function for headers, there doesn't seem to be one for payloads and frames.  It's generally not a great idea to copy entire frames, but Dana just wanted to do it to create dummy frames with the same size and shape as the ones she's analyzing.  Maybe worthwhile to consider.

**Comment by mhvk** [comment]
No reason not to have a `copy` method, indeed. Of course the work-around is simply
```
copy = old_frame.__class__(old.header, old.payload, old.valid, verify=False)
```
But it might make sense to also allow payloads and frames to be immutable.

**Comment by cczhu** [comment]
We run into problems for copying DADA payloads, though.  Is there a way to copy a `numpy.memmap` without re-opening the file?

**Comment by mhvk** [comment]
I think for `DADA`, this may have to fall in the "don't do this!" category... More seriously, maybe check with Dana how exactly she wants to use this.

**Comment by cczhu** [comment]
She's already found a workaround.  The method for copying frames was more me wanting Baseband to be complete.  However if it's prohibitive for some payloads to be copied maybe we just shouldn't implement, or should wait until we have a `base` separate from `vlbi_base`.

**Comment by mhvk** [comment]
I must admit I cannot quite see why one would want to have a `copy` method for the payload (and thus for the frame). So let's close this for now.
