### ISSUE TITLE
Change VDIF frameset output array ordering?

### ISSUE THREAD

**Issue by mhvk** [mhvk/baseband#129]
Currently, `VDIFFrameSet.data` has order `threads, samples, channels` - it might make more sense to make `samples` the first dimension, like everything else. That way the main code in the streamreaders can be more similar to that of other formats, and one avoids having to do a `transpose` there before any slicing (thus enforcing decoding of all frames in the set even if only parts are needed).

(Inspired by #108 and #118)

**Comment by cczhu** [comment]
I was thinking the same thing, and will look into this shortly.

**Comment by mhvk** [comment]
Being addressed by #166
