### ISSUE TITLE
Make fill_value a property of the file handle

### ISSUE THREAD

**Issue by mhvk** [mhvk/baseband#146]
There would seem to be a great benefit of `fh.read(...)` to have only arguments that are valid for all formats. We've gone partially that way by moving `squeeze` up and I think we should continue that by also moving `fill_value` to be an argument of `open` rather than of `read` (this in particular since `gsb` does not have a fill value; #105). I think initially at least I would advocate for not making this settable after opening the file (though that is not hard to do in principle; it would require invalidating any frame already decoded, though).

**Comment by theXYZT** [comment]
I'll do this one!

**Comment by theXYZT** [comment]
The DADA fill format doesn't seem to use `fill_value` currently. Should I add it in anyway?

**Comment by mhvk** [comment]
Indeed, nor does `gsb` - my sense right now would be to implement it only for the formats that support it, so mark4, mark5b, and vdif (we can easily add an argument later if we want to have a general `baseband.open`). Since the value should be passed on to `vlbi_base`, you should be sure to give it a default of 0 there (which means that `dada` and `gsb` will inherit the `fill_value` property, but that is OK).

**Comment by theXYZT** [comment]
PR made at #163, tests complete successfully.
