### ISSUE TITLE
mark5b stream reader cannot detect sample rate

### ISSUE THREAD

**Issue by ramain** [mhvk/baseband#150]
Opening a large (9min) mark5b file with correct channels and reference time (e.g. mark5b.open(fn, 'rs', nchan=8, ref_time=ref_time) ), fails with message  " KeyError: ('Mark5BHeader header does not contain seconds', 'the sample rate could not be auto-detected. This can happen if the file is too short to determine the sample rate, or because it is corrupted.  Try passing in an explicit `sample_rate`.') "

The stream reader still works when explicitly giving the sample_rate, but the file is uncorrupted and long, and should be able to infer the sample_rate.

**Comment by mhvk** [comment]
@cczhu - the underlying issue is the change of `header.seconds` to `header['seconds']` in `_get_frame_rate` -- after looking at this, we decided simply not to look at the seconds - it would be up to the caller to do sanity checks on the guessed frame rate.

**Comment by mhvk** [comment]
See #151

**Comment by mhvk** [comment]
Mostly fixed by #151, but still needs to add a regression test so leaving it open for now. See https://github.com/mhvk/baseband/pull/151#issuecomment-373770322

**Comment by mhvk** [comment]
test now added, so closing. Thanks, @ramain!
