### ISSUE TITLE
Factor out `read` and `write` to `StreamReaderBase`

### ISSUE THREAD

**Issue by mhvk** [mhvk/baseband#156]
Currently, the code of `read` and `write` is nearly identical for the different formats, which suggests the method can be moved up, as long as one keeps any format-specific frame checking in the file formats (likely, in `_read_frame`).

**Comment by cczhu** [comment]
This will be more tractable once #129 is resolved.  (I also saw that I wrote "I will look into this shortly" there...)

**Comment by mhvk** [comment]
As I was looking at the code anyway: what I mainly think is needed is that `read` does not itself check whether the currently loaded frame is the right one, but rather just calls a (say), `_get_frame()` method, which does the check (based on `offset`) and, if needed, loads a new frame.

**Comment by cczhu** [comment]
Read was solved by #169.

**Comment by mhvk** [comment]
write was resolved by #172, so closing
