### ISSUE TITLE
Reserve size for total number of samples

### ISSUE THREAD

**Issue by mhvk** [mhvk/baseband#167]
I was thinking that perhaps frame, payload should be even closer to arrays, by having the appropriate `__len__` and `size`. But we use `size` for number of bytes as well. Arguably, that is much less useful to the typical user, so one solution would be to rename that. E.g., `encodedsize` (the `.payloadsize` and `.framesize` of a header could stay that way).

**Comment by cczhu** [comment]
I believe this and #168 are resolved by PR #169.

**Comment by mhvk** [comment]
#168 was indeed resolved by #169, but this one is not: the question is whether frames and payloads should have a `size` that gives the total number of samples or the total number of bytes.

**Comment by mhvk** [comment]
Decision: yes, so current `size` -> `nbytes` for header, payload, frame

`payloadsize` -> `payload_nbytes`
`framesize` -> `frame_nbytes`

**Comment by mhvk** [comment]
fixed by #199
