### ISSUE TITLE
For binary readers, pass on kday, nchan etc on file opening

### ISSUE THREAD

**Issue by mhvk** [mhvk/baseband#170]
The advantage might be that `read_frame` etc. don't need it any more, and would (I think) more easily used from the stream reader class. For formats like mark4, it also means one can more readily use `determine_ntrack()` (no reason not to be able to try that for the binary reader upon opening a file).

**Comment by cczhu** [comment]
By this, do you mean that binary readers would have `kday`, `nchan`, etc, as attributes?  I see the appeal, but also like that the binary reader is bare-bones except for the methods it adds.  If anything, I'd actually prefer methods like `determine_ntrack` to be stream reader-only.

**Comment by mhvk** [comment]
Yes, that is what I meant, i.e., one might as well provide at least defaults for `read_frame` etc. The slight advantage would be that in the stream reader we can provide a common `_read_frame` method.

I do think `determine_ntrack` belongs on the binary file reader, since it does not need any information about sample organization (which is what the stream reader provides), and it helps inspecting a raw file.

**Comment by mhvk** [comment]
See #184 for an implementation. It does bring up the old wonder of whether it wouldn't be better to wrap rather than subclass the binary file reader/writers...

**Comment by mhvk** [comment]
closing since being fixed by #187
