### ISSUE TITLE
Inconsistent use of rounding?

### ISSUE THREAD

**Issue by cczhu** [mhvk/baseband#210]
For certain routines, `np.round()` (or `<myarray>.round()`) is used to round values, while for others Python's built-in `round` is used.  For Python 2, Numpy rounds to the nearest even integer, while the built-in round always rounds 0.5 down to 0.  For Python 3, they both use convergent rounding.

Happily there aren't too many situations where we round exactly 0.5, but it would be reasonable to standardize everything to `np.round`, even if that routine is slightly slower than built-in.

**Comment by mhvk** [comment]
I think the next release is going to be python3-only, so I don't think we have to worry about this except perhaps as a bug-fix for 1.0.1.

Another argument for `np.round` might be that it more easily allows extension to arrays of headers, etc.

**Comment by mhvk** [comment]
closing since worry about inconsistent rounding seems theoretical.
