### ISSUE TITLE
Mini-change: format-specific docs should mention generic opener

### ISSUE THREAD

**Issue by cczhu** [mhvk/baseband#221]
Right now they only mention `<FORMAT>.open`.  Since users aren't guaranteed to look at Getting Started, all docs should mention both (adding examples is unnecessary).

**Comment by georgestein** [comment]
Hey Charles, i'd like to contribute to this for Martens mini coding course.

For clarification before I take a stab, are you referencing e.g. /baseband/docs/dada/index.rst, where it says things such as: "Single files can be opened with `~baseband.dada.open` in binary mode." should be modified to state the general case, where just baseband.open can also be used without specifying the data type?

So change it to something like "Single files can be opened with `~baseband.dada.open` (or the general`~baseband.open` function) in binary mode"...?

**Comment by cczhu** [comment]
Solved by #230; closing.
