### ISSUE TITLE
Mini-change: move `np.memmap` tests into `with` blocks

### ISSUE THREAD

**Issue by cczhu** [mhvk/baseband#226]
Another branch off of #212 - currently in the DADA (and soon the GUPPI) test suites, we create memmaped frames within `with open(...) as ...` blocks, but then continue to use the frames after the files have been closed (I imagine the memmap has its own filehandle that remains open).  Formally speaking we shouldn't have these loose file handles around, so all memmapping should be done within `with` blocks.

**Comment by mhvk** [comment]
Upon further discussion, frames should be accessible just like they would be if they had read in the data. So, closing.
