### ISSUE TITLE
Move sequential file reading ability to `opener`

### ISSUE THREAD

**Issue by cczhu** [mhvk/baseband#231]
As I just saw a large number of sequential VDIF files, it might be useful to have any format's `open` take a tuple of filenames, or a template.  This would involve:

- Creating an abstract opener that also works with sequential file and file templates, essentially a generalization of the DADA/GUPPI opener.
- Create an abstract `FileNameSequence` class in `sequentialfile`, which can be inherited by DADA.  This function would only have the ability to produce sequences of increasing file number - the inherited classes are responsible for reading header keywords for fancier iteration.
- Keep `open` a function, and `opener` its generator.  This would mean we need a format-specific preprocessor (mainly for DADA) to figure out how to deal with `kwargs` when a template is passed in.  This should go in `FileNameSequence` itself, though.

**Comment by cczhu** [comment]
So past me is more ambitious than current me - we've generalized both `FileNameSequencer` and `make_opener` to handle any sequential file opening, except for templates.

Past me suggested that `FileNameSequencer` or its subclasses can deal with using the `kwargs` to read the first file of the sequence represented by a template, but we also need to pass non-header `kwargs` to the file opener to set things like `nthread` for VDIF.  In practice, this considerably over-complicates `FileNameSequencer` or its subclasses, as well as `make_opener`, as can be seen in the prototype `sequentialfile_for_all` branch in my repo of Baseband.  (For example, `make_opener` needs to know the keyword arguments for the stream readers and writers of each format.)  #253 and #254 go most of the way toward generalizing sequentialfile reading, but don't generalize template reading.  Since there doesn't appear to be a commonly-used template for the VLBI formats, I don't think this is a major loss of functionality, and think we should close this once those PRs go through.

**Comment by mhvk** [comment]
fixed by #253 and #254
