### ISSUE TITLE
Subclass GUPPI frame and payload classes from DADA?

### ISSUE THREAD

**Issue by cczhu** [mhvk/baseband#234]
Currently frame and payload classes for GUPPI are very similar (though for payload not identical).  In particular, now that we've made some fixes to the DADA frame class, its `fromfile` and `tofile` methods are identical.

This could be part of a bigger push to separate universal `base` classes from `vlbi_base`, and to create `vlbi_base` and `dada_base` classes that derive from the universal one. #259

**Comment by mhvk** [comment]
Clarification: plan currently is for a `LargePayload` or `MemmapPayload` class that both dada and guppi inherit from, i.e., guppi would not inherit from dada directly. But can be revisited if needed.

**Comment by mhvk** [comment]
fixed by #427
