### ISSUE TITLE
Reading partial last frame from GUPPI?

### ISSUE THREAD

**Issue by cczhu** [mhvk/baseband#238]
Follow-up to #228, where we implemented the ability to read a partial DADA frame if it's the last (or only) frame in the observation.  We want to have the same capability for GUPPI, but it's not possible to handle channels-first data using the same algorithm (unless GUPPI's acquisition system can write a partial channels-first frame, which would be remarkable).  We therefore need to explore alternate methods.

**Comment by mhvk** [comment]
Guppi's frames are far less long than DADA's so I'd vote for just ignoring the last frame if it is `channels_first`.

**Comment by cczhu** [comment]
I don't think we've encountered a time-ordered GUPPI frame, so maybe we should table this enhancement until we do?

**Comment by mhvk** [comment]
Might still be good to at least ignore a last frame being cut off, although I'm also happy to postpone until we actually find such an observation.

**Comment by cczhu** [comment]
That's actually GUPPI's current behaviour, though apparently there isn't a test for it.  I'll make a new PR for that.

Since we've never encountered a GUPPI stream with `header['PKTFMT'] == 'simple'`, I think we can close this issue once I've uploaded the PR.  We can always re-open it when we encounter time-ordered data.

**Comment by cczhu** [comment]
Solved by #212 and #242.
