### ISSUE TITLE
`baseband.test()` leaves residual files

### ISSUE THREAD

**Issue by cczhu** [mhvk/baseband#255]
Currently under an python or IPython environment (in either py2 or py3), doing:

```
import baseband
baseband.test()
```
will leave `file0.raw`, `file1.raw`, `file2.raw` and a `v` folder of other stuff.  Can this be cleaned up by the tests before completion, so the user doesn't have to deal with it?

**Comment by cczhu** [comment]
All the various `tmpdir` issues in our test suite have been fixed, but there's still the `v/cache/nodeids` file.  This is produced by pytest itself as [part of its cache](https://docs.pytest.org/en/latest/cache.html).  I'm not sure what the most reasonable way to suppress that is, and will raise an issue on astropy-helpers.

**Comment by cczhu** [comment]
Upon further testing, a barebones virtualenv using
```
astropy==2.0.3
attrs==18.1.0
baseband==1.1.1
numpy==1.14.1
pluggy==0.6.0
py==1.5.4
pytest==3.4.2
six==1.11.0
```
doesn't leave `v`, while one using `pytest==3.5.0` and beyond does, so this is either an astropy-helpers problem or a pytest problem.

**Comment by cczhu** [comment]
Okay, this is potentially solved by updating astropy-helpers to 2.0.7.  Making a PR now.

**Comment by mhvk** [comment]
Sounds like you have enough for an issue on astropy helpers...

**Comment by mhvk** [comment]
Did you raise an upstream issue?  If so, can we link here, and maybe add a label "upstream fix required"?

**Comment by mhvk** [comment]
No longer an issue with more recent astropy, so closing.
