### ISSUE TITLE
`baseband.test()` with pytest 3.7.x and astropy 2.0.x unable to collect items

### ISSUE THREAD

**Issue by cczhu** [mhvk/baseband#267]
In a barebones Python 2.7 or 3.5 virtualenv created using:
```
virtualenv --no-site-packages --python=python basepy2
source basepy2/bin/activate
pip install baseband
pip install pytest-astropy
```
when running
```
import baseband
baseband.test()
```
in the interpreter, no items are found during Pytest's collection phase, and so no tests are run.

Reverting to `pytest==3.6.x` fixes this issue.  For Python 3, upgrading to `astropy==3.0.4` also fixes it.  This may be directly related to #255, and thus a fix might already exist.

**Comment by mhvk** [comment]
Closing since fixed in more recent versions.

**Comment by cczhu** [comment]
Hooray!
