### ISSUE TITLE
Baseband throws errors when using irrelevant arguments for `.open()`

### ISSUE THREAD

**Issue by theXYZT** [mhvk/baseband#322]
It seems the intended use of `.open()` in `baseband` requires the user to provide exactly the right arguments to read the file formats. This is annoying when you are trying to automate the reading to multiple file formats since it would be useful to be able to give all arguments to the relevant `.open()` function and have `baseband` ignore the arguments that are irrelevant.

For example, the following raises an error:
`fh = guppi.open(fs, 'rs', sample_rate=3.125 * u.MHz)`

since `sample_rate` is an unexpected keyword. It would be desirable for the `.open()` function to just ignore the keyword argument. While, this doesn't seem to be a huge issue here, it is a problem when using `baseband.open()` and rotating between multiple file formats (say, in a VLBI dataset) and having to curate the keyword arguments.

Currently, `baseband.open()` explicitly throws an error when detecting irrelevant keyword arguments, when it would be better if it just ignored them (having detected them as irrelevant).

**Comment by mhvk** [comment]
I would be happy to have this be controlled, and for something like `sample_rate`, it would be fine to count it among the kwargs that need to be consistent. The code is in `baseband/core.py`...

**Comment by mhvk** [comment]
@theXYZT - thought a bit more about this - I think I would be quite happy for the general opener to only warn instead of raising an error; then the user can decide to either silence the warning, or raise on it. But only for the "irrelevant" kwargs. Do you want to make a PR? cc @00rebe

**Comment by mhvk** [comment]
I'm looking at this again and wondering what the actual problem is. In your example, does
```
fh = baseband.open(fs, 'rs', sample_rate=3.125 * u.MHz)
```
actually fail? That would be a bug (but it doesn't cause any problem on the sample puppi file included in baseband).

But I'm not sure one should just warn on arguments that have no meaning for any of the file formats - that is contrary to how functions in python work.

**Comment by mhvk** [comment]
Just confirmed: it does all seem to work!
