### ISSUE TITLE
wrong MemoryError message

### ISSUE THREAD

**Issue by tcassanelli** [mhvk/baseband#338]
I'm reading data from ARO and I've been having this issue:

```Traceback (most recent call last):
  File "/home/v/vanderli/cassane/babendil-frb-vlbi/scripts/gp_search.py", line 123, in <module>
    gp_size=128
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/babendil-0.0.1-py3.7.egg/babendil/sigprocess/gp_finder.py", line 262, in finder
    V_cdd = self.process_file(timestamp, ntime)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/babendil-0.0.1-py3.7.egg/babendil/sigprocess/gp_finder.py", line 189, in process_file
    verify=True
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/babendil-0.0.1-py3.7.egg/babendil/io/reader.py", line 93, in read_ntime
    V = fh.read(ntime)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/scintillometry-0.0.dev321-py3.7.egg/scintillometry/base.py", line 311, in read
    self._frame = self._read_frame(frame_index)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/scintillometry-0.0.dev321-py3.7.egg/scintillometry/base.py", line 554, in _read_frame
    data = self.ih.read(self._raw_samples_per_frame)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband/vlbi_base/base.py", line 561, in read
    self._frame = self._read_frame(frame_index)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband/vdif/base.py", line 468, in _read_frame
    verify=self.verify)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband/vdif/base.py", line 125, in read_frameset
    verify=verify)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband/vdif/frame.py", line 245, in fromfile
    payload = VDIFPayload.fromfile(fh, header=header)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband/vdif/payload.py", line 180, in fromfile
    s = fh.read(header.payload_nbytes)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband/helpers/sequentialfile.py", line 278, in read
    extra = self.fh.read(count)
MemoryError
```

which sounds like a classic `MemoryError`. I am currently opening `2 ** 20` number of samples (where it shouldn't complain) (I closed the `.vdif` and there were no other variables using RAM). Now, when I open another timestamp from the same data set I don't get the error. Seems like baseband is raising the `MemoryError` instead of an `AssertionError` or another type of error?
I haven't identified which file is giving this error explicitly since I am using a stream reader, but I will do soon.

**Comment by mhvk** [comment]
Very weird. Could you use the debugger and check what `count` is in that read statement? To help further, I'd need a more minimal example (or we can sit together with an example that has the problem).

**Comment by tcassanelli** [comment]
I noticed that while using `baseband.helpers.sequentialfile.open` the error persists, but if I use `baseband.vidif.open` for single files I can read with no problem. I also tried by setting the argument `verify=False` and it did not go through. Is there anything else that I could do to debug this problem? The error log is basically what I showed in the previous post.

**Comment by mhvk** [comment]
Do point me to the set of files - I wonder if it is something specific about those.

p.s. Does the problem persist if you only open a subset?

**Comment by tcassanelli** [comment]
I am using these set of files on `scinet`:
```python
path2data = (
'/scratch/v/vanderli/cassane/VLBI_data/Aug2019_10m/20190813T155543Z_aro_vdif/*.vdif'
)
```
(let me know if you have access to it). The error shows up while opening from the timestamp: 

```python
form astropy.time import Time
timestamp = Time('2019-08-13T15:55:45.669437440', scale='utc', precision=9)
```
up to `2 ** 20` number of samples. `timestamp` is located in the `617446` sample.
 Then I tested by opening a smaller subset, I could narrow it down to:
```python
from astropy import units as u
from baseband import helpers, vdif
fraw = helpers.sequentialfile.open(data_sorted, 'rb')
freq_resolution = 390625 * u.Hz
fh = vdif.open(fraw, mode='rs', sample_rate=freq_resolution, verify=True)
fh.seek(1133662)
fh.read(1000)

MemoryError
```
where `data_sorted` are the sorted files in `path2data` directory. In summary the error could be around the file `1133662 / 32768` (~34) I think, i.e. `data_sorted[34]`.

**Comment by mhvk** [comment]
@tcassanelli - am getting back to old issues and was hoping to check your error, but I don't have access to the data on `niagara`. Could you change the permissions?

**Comment by tcassanelli** [comment]
@mhvk I gave you permission again, not sure if it works, I'm using the username `mhvk`, let me know if it works now.

**Comment by mhvk** [comment]
@tcassanelli - this may have been solved with #357, but am not sure. Could you check? (I.e., use current master of baseband). If things are OK, I'm hoping to release this as part of baseband 3.1 soon. Otherwise, I'll try to get a fix for this too...

**Comment by tcassanelli** [comment]
I just checked this past error, and it seems to have the same error as my post in `scintillometry` (https://github.com/mhvk/scintillometry/issues/145#issue-552547831). I basically run this code https://github.com/mhvk/baseband/issues/338#issuecomment-547107196, and I got the same error:

```
ValueError                                Traceback (most recent call last)
<ipython-input-27-4acfecf3894a> in <module>
      5 fh = vdif.open(fraw, mode='rs', sample_rate=freq_resolution, verify=True)
      6 fh.seek(1133662)
----> 7 fh.read(1000)

~/anaconda3/lib/python3.7/site-packages/baseband-3.0.dev1076-py3.7.egg/baseband/vlbi_base/base.py in read(self, count, out)
    786                                                 self.samples_per_frame)
    787             if frame_index != self._frame_index:
--> 788                 self._frame = self._read_frame(frame_index)
    789                 self._frame.fill_value = self.fill_value
    790                 self._frame_index = frame_index

~/anaconda3/lib/python3.7/site-packages/baseband-3.0.dev1076-py3.7.egg/baseband/vlbi_base/base.py in _read_frame(self, index)
    838         if frame_index != index:
    839             return self._bad_frame(index, frame,
--> 840                                    ValueError('wrong frame number.'))
    841
    842         # In either case, we check the next frame (if there is one).

~/anaconda3/lib/python3.7/site-packages/baseband-3.0.dev1076-py3.7.egg/baseband/vdif/base.py in _bad_frame(self, index, frameset, exc)
    535
    536         if self.verify != 'fix':
--> 537             raise exc
    538
    539         msg = 'problem loading frame set {}.'.format(index)

ValueError: wrong frame number.
```

**Comment by mhvk** [comment]
It is still very weird that before you got a `MemoryError`... But that has now disappeared?

In any case, it would still be good to have a look at the file, but unfortunately, I don't seem to be able to access it...:
```
mhvk@nia-login05:~$ ls -l /scratch/v/vanderli/cassane/VLBI_data/Aug2019_10m/20190813T155543Z_aro_vdif/
ls: cannot access /scratch/v/vanderli/cassane/VLBI_data/Aug2019_10m/20190813T155543Z_aro_vdif/: Permission denied
```

**Comment by tcassanelli** [comment]
yes `MemoryError` has now disappear with the new `baseband` version. I will try to give you access again.

**Comment by mhvk** [comment]
Closing this for now, since the problem seems to have disappeared.

**Comment by tcassanelli** [comment]
FYI, I tried again with the new `baseband` version 3.1 and I still get the same error, if I use `verify=False` it returns `MemoryError`.  Same example as in https://github.com/mhvk/baseband/issues/338#issuecomment-547107196. Perhaps I could copy a couple of those files to `cita`? since `scinet` doesn't let me give you access (I'll contact IT).

**Comment by mhvk** [comment]
OK, reopening this issue. My suspicion is that there is a corrupt header which tells that there is a huge payload, which doesn't fit in memory. Possibly this can be circumvented if I still do the valid header check even if `verify=False`. Though really `verify=False` was meant to be for the case that you know the data is OK.

**Comment by mhvk** [comment]
Closing since no progress
