### ISSUE TITLE
Baseband tests fail on Windows due to OSError

### ISSUE THREAD

**Issue by theXYZT** [mhvk/baseband#376]
Currently, baseband does not pass tests on Windows systems purely due to poor management of file paths in some tests.

The error log can be found here: https://gist.github.com/theXYZT/9bd177424cdff9e90fb2b43afaf28e1e

One example of poor path management would be the first error in `baseband/dada/tests/test_dada.py` line 251 where a new filename is created via: `filename = str(tmpdir.join('a.dada'))` which immediately fails when used in `open()` on any system not using POSIX-style paths. Quickly skimming through the errors, they all seem to occur when a similar `string.join` operation is used to make paths.

A simple solution would be to use `pathlib`  and convert string-based paths to proper Path objects: 
```
from pathlib import Path
filename = Path(filename)
```

Optionally, we could also use this in the package itself in the following two files: `baseband/helpers/sequentialfile.py` and `baseband/vlbi_base/base.py` so that you don't have change the way you write tests.

---

Note: The above tests were done using `baseband.test()`. I also ran `tox -e test` on the source code and got similar errors.

**Comment by mhvk** [comment]
Yes, I don't have windows so it never gets tested, but would very happily get a PR. That could include changing one of the travis runs to windows so it stays OK.

**Comment by mhvk** [comment]
Just keeping track: things may be easier if we move to the new `tmp_path` fixture of pytest: https://docs.pytest.org/en/latest/tmpdir.html#tmpdir-handling

**Comment by theXYZT** [comment]
I have been looking into this and am generally confused about what the error even is. I am not sure it's a problem with paths anymore.

Here's an example (from `test_guppi.py`):

```
filename = str(tmpdir.join('testguppi.raw'))
with guppi.open(filename, 'wb') as fw:
    fw.write_frame(frame)

with guppi.open(filename, 'rb') as fw:
    frame3 = fw.read_frame()

assert frame3 == frame
# Now memmap file to be written to.
with guppi.open(filename, 'wb') as fw:
    frame4 = fw.memmap_frame(frame.header)
```

The test fails on the final `guppi.open()` (second-to-last line on the code snippet). This doesn't make sense to me as the exact same file with identical path has been opened at least twice (once to write and once to read) before successfully. Why would it fail the third time?!

**Comment by mhvk** [comment]
Could it be that the problem is that the file exists already? It may be that the behaviour on Windows for existing files is different. Looking at the code snippet, it certainly seems like a different name there would be more logical.

p.s. If you want to open a PR with a change to `.travis.yml` to include a windows run, that would be fine. I'm definitely not against making sure it works on windows, just don't want to be the one spending the time to make it work!

**Comment by theXYZT** [comment]
I figured it out!

The following code fails with an OSError
```python
from baseband import guppi
filename = 'sample_test.raw'

with guppi.open(filename, 'rb') as fr:
    frame = fr.read_frame()

with guppi.open(filename, 'wb') as fw:
    pass
```

and the following code passes with no errors:
```python
from baseband import guppi
filename = 'sample_test.raw'

with guppi.open(filename, 'rb') as fr:
    frame = fr.read_frame(memmap=False)

with guppi.open(filename, 'wb') as fw:
    pass
```

It seems, at least on my system, you are not allowed to "write to a file" that is currently being memory-mapped. This makes sense to me and it's actually surprising that this test would pass on Linux systems. It's seems like a feature, not a bug, of an OS to lock a file that's it currently being memory-mapped!

**Comment by mhvk** [comment]
That's great! And I agree it is a bug on linux: if after executing your top example, I try:
```
In [6]: frame                                                                                                                                                
Out[6]: <baseband.guppi.frame.GUPPIFrame at 0x7f0d78bfba00>

In [7]: frame.data                                                                                                                                           
Bus error
```
And I'm out of python... (accessing data will actually try to access the file content).

Now I need a non-baseband example for a bug report...

**Comment by theXYZT** [comment]
If frame.data returns an error, then how do the frame comparison assertions work for the test?

**Comment by mhvk** [comment]
See https://bugs.python.org/issue40720

I think the test handily avoided testing the frame after writing to the file (frame3 does not get accessed after opening the file it points to for writing).

**Comment by theXYZT** [comment]
Yay! This strange experiment is somehow contributing to Python in general!

PS: This just strengthens my belief that Windows is a good OS to develop code in!
