### ISSUE TITLE
Should readers/writers be indexable?

### ISSUE THREAD

**Issue by mhvk** [mhvk/baseband#396]
One could define `__getitem__` and `__setitem__`, but one should the semantics be? One option is to return an array, i.e., the equivalent of `seek(start); read(stop-start)`, the other to return a new instance that sees only a part of the file. If one also defined an `__array__`, this might look similar for most purposes, and it *might* be handier for interaction with `dask`, hence cc @theXYZT.

EDIT: also nice of either scheme is that it will become possible to do `writer.write(stream)`, which feels a bit nicer than the `stream.read(out=writer)` I implemented for `hdf5`. For the `.write`, it will also be easier to limit the number of samples copied per iteration, by having some `max_samples_per_iteration` or so.

**Comment by theXYZT** [comment]
I would love to have indexable readers/writers. I think it should return an array via `seek()` and `read()` since that is the most common use for indexing. However, it think this only has value if it also supports indexing on all dimensions, not just the along the samples.

If I have, `fh.shape = (1024, 2, 4)`, I should be able to call `fh[:, 0, 0]` and return the corresponding subset of the entire file, as so on.

> the other to return a new instance that sees only a part of the file

This is interesting (and I see how it intuitively "slices" the reader/writer instances) but I don't see the benefits/uses.

**Comment by mhvk** [comment]
Well, Thierry is divvying up CHIME VDIF files in multiple separate parts - for that indexing might help. But really, I was mostly thinking in the context of `dask`, which wants chunkable arrays, and I want to be sure I don't destroy interacting well with it by returning arrays (maybe a dask array would be better???)

**Comment by theXYZT** [comment]
For slicing the file reader object itself (something I would be interested in too), it makes sense to have a different explicit method rather than trying to achieve it via `__getitem__()`.

In my opinion, numpy-style slicing should always return array-like objects, and indexing via `__getitem__()` should return a result consistent with the existing `.shape`, `.dtype`, and `.ndim` attributes.

With regards to using `dask`, as long as you can use the `out` argument in `.read()` to point to a dask array, it should be fine. Similar to how when I want fortran-ordered arrays, I use the `out` argument as well. I don't think the indexing via `__getitem__()` would affect `dask` usage much.

**Comment by mhvk** [comment]
OK, that makes sense. As I already defined a `__setitem__` in an array-like context for the [hdf5 writer](https://scintillometry.readthedocs.io/en/latest/io/hdf5/index.html), it certainly is quite symmetric...

On the slicing to get a different reader, at the basic level one can already pass a `subset` to the reader, and also there is [`GetItem`](https://scintillometry.readthedocs.io/en/latest/api/scintillometry.shaping.GetItem.html#scintillometry.shaping.GetItem), though that only slices the sample shape.

For most readers, there is little advantage to knowing what to slice, since the data have to be all read and usually all decoded anyway (VDIF is the only exception, where at least in some files, the subbands are in different threads, which one can skip).

**Comment by theXYZT** [comment]
The more I think about it, the more I like the idea of using slicing to return reader/writer objects. One reason is that Numpy-like slicing returns a view, and a restricted "file reader object" seems like a "view". It could be annoying if simply doing `fh[:2**20]` resulted in a long wait while it creates and populates an array. Whereas if all it did was return a "view" into the reader object by returning a restricted reader, that would be nice.

The following usage is what I have in mind:
```
fh = baseband.open(...) # Some reader
block = fh[start:stop, subset...] # Reader instance that only sees the file from start to stop and only at the given subset
block.read(out=...) # To finally create and populate an array with data
```

Of course, we don't have to use slicing to do this at all. But the use case of a having a smaller reader/writer instance restricted to a certain span of samples and a certain subset in the sample shape is nice.

**Comment by mhvk** [comment]
Ah, now you see my conundrum! It may be good to check if one can have the cake and eat it too, by also defining an `__array__` method (which would by default read the whole thing...)

**Comment by theXYZT** [comment]
> Ah, now you see my conundrum! It may be good to check if one can have the cake and eat it too, by also defining an `__array__` method (which would by default read the whole thing...)

So, `z = np.array(fh)` would simply be equivalent to `z = fh.read()`?

**Comment by mhvk** [comment]
The reason at some point I thought returning an array might make sense is that I thought `dask.array.from_array(fh, chunks=...)` would work better in that case. But actually, mocking them both, the index-returns-a-reader works just as well as long as `__array__` is defined:
```
import numpy as np
from dask import array as da
import baseband
import baseband.data
from scintillometry.base import BaseTaskBase


class Subset(BaseTaskBase):
    def __init__(self, ih, item):
        self.sample_slice = (slice(None),)+item[1:]
        self._start = item[0].start
        start_time = ih.start_time + item[0].start / ih.sample_rate
        samples_per_frame = item[0].stop-item[0].start
        shape = (samples_per_frame,) + ih.sample_shape
        super().__init__(ih, start_time=start_time, shape=shape,
                         samples_per_frame=samples_per_frame)

    def _read_frame(self, index):
        self.ih.seek(self._start + index * self.samples_per_frame)
        return self.ih.read(self.samples_per_frame)[self.sample_slice]

    def __array__(self, dtype=None):
        self.seek(0)
        return self.read()


class GetItemGivesArray:
    def __init__(self, fh):
        self.fh = fh
        self.shape = fh.shape
        self.ndim = fh.ndim
        self.dtype = fh.dtype

    def __getitem__(self, item):
        self.fh.seek(item[0].start)
        data = self.fh.read(item[0].stop-item[0].start)
        return data[(slice(None),)+item[1:]]


class GetItemGivesFH(GetItemGivesArray):
    def __getitem__(self, item):
        return Subset(self.fh, item)


fh = baseband.open(baseband.data.SAMPLE_VDIF, 'rs')
data = fh.read()

dh = GetItemGivesArray(fh)

a1 = da.from_array(dh, chunks=(fh.samples_per_frame,)+fh.sample_shape,
                   lock=True, fancy=False, asarray=False)

s1 = (a1**2).sum(0)

ih = GetItemGivesFH(fh)

a2 = da.from_array(ih, chunks=(fh.samples_per_frame,)+fh.sample_shape,
                   lock=True, fancy=False, asarray=True)

s2 = (a2**2).sum(0)

expected = (data**2).sum(0)
print('getitem-gives-array', np.allclose(s1.compute(), expected))
print('getitem-gives-reader', np.allclose(s2.compute(), expected))
```

**Comment by theXYZT** [comment]
I agree and prefer returning a reader with an __array__() method defined - because I think it preserves the lazy execution. If fh[100:200] just eagerly returned an array, I am forced to hold the returned array in memory when calling da.from_array(fh[100:200]).

**Comment by mhvk** [comment]
Also, it might well be that if the reader returned is actually a new instance, one wouldn't need the lock (as is, the stream readers are not thread-safe, but I tried a quick hack and it turned out it didn't help because the python binary file readers are also not thread-safe; with a new instance that would be solved).

**Comment by mhvk** [comment]
To add in favour of returning a more limited reader: that make much more sense in the `scintillometry/baseband-tasks` sense. E.g., I would be quite happy if the following "just worked":
```
fh = baseband.open(...)
wf = np.sum(np.reshape(np.square(fh), (-1, 10)+fh.sample_shape), axis=1)
actual_data = wf.read()
```

**Comment by mhvk** [comment]
I've used the `__getitem__` returns stream and `__array__` turns the whole thing into an array in `baseband-tasks` -- https://github.com/mhvk/baseband-tasks/pull/192 and https://github.com/mhvk/baseband-tasks/pull/194

So far, things look good, but I prefer to check how things shake out before going there for `baseband` proper; it would need moving over quite a bit of stuff from `*-tasks`. Logic right now would be something akin to
```
from baseband.tasks import SetAttribute
wrapped = SetAttribute(fh, frequency=..., sideband=..., polarization=...)
```
and then `wrapped` is sliceable and array-able.

**Comment by mhvk** [comment]
Coming back to this after a year, I think the base baseband readers should remain simple and look as much as possible like file-readers. Since the indexing is now very easily possible with `baseband-tasks`, which is a pretty lightweight extension, I'll close this.
