### ISSUE TITLE
IndexError of fh_rd.start_time of the GSB data

### ISSUE THREAD

**Issue by hsiuhsil** [mhvk/baseband#452]
When using the version baseband==4.1.dev10+g99aa797 to read the GSB file, printing out the fh_rd_start_time would give an IndexError.
`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-8a9d0aae621d> in <module>()
      7                       [base+'Pol-R1.dat', base+'Pol-R2.dat']])
      8 
----> 9 print(fh_rd.start_time)
     10 print(fh_rd.info())
     11 

/scinet/niagara/software/2018a/opt/base/anaconda3/5.1.0-hub/lib/python3.6/site-packages/astropy/time/core.py in __str__(self)
    443 
    444     def __str__(self):
--> 445         return str(getattr(self, self.format))
    446 
    447     @property

/scinet/niagara/software/2018a/opt/base/anaconda3/5.1.0-hub/lib/python3.6/site-packages/astropy/time/core.py in __getattr__(self, attr)
   1129                 else:
   1130                     tm = self.replicate(format=attr)
-> 1131                 value = tm._shaped_like_input(tm._time.to_value(parent=tm))
   1132                 cache[attr] = value
   1133             return cache[attr]

~/baseband/baseband/gsb/header.py in to_value(self, parent)
     55         iys, ims, ids, ihmsfs = erfa.d2dtf(scale, self.precision,
     56                                            self.jd1, self.jd2)
---> 57         ihrs = ihmsfs['h']
     58         imins = ihmsfs['m']
     59         isecs = ihmsfs['s']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
`

**Comment by mhvk** [comment]
@hsiuhsil - can you check the version of astropy? 
`python3 -c 'import astropy; print(astropy.__version__)'`

the newer baseband requires astropy >= 4.0. Though it is quite possible I introduced a bug, as I did a lot of refactoring.

**Comment by hsiuhsil** [comment]
Thanks @mhvk, the issue is solved once I update the astropy with the version of 4.0.1.
