### ISSUE TITLE
Creating a new StreamReader object from an existing one.

### ISSUE THREAD

**Issue by theXYZT** [mhvk/baseband#461]
If I create a StreamReader object by doing: `fh = guppi.open(name, 'rs', **kwargs)`, I want to create another StreamReader object given only `fh`. This is useful if you want the new StreamReader to have different properties, for example a different `subset`.

Currently, the way I would do it is: `fh2 = guppi.open(fh.fh_raw.name, ...)`. Is this correct? Am I missing an edge case where this would cause problems?

Is there another way of doing this that was intended in the API that I am missing?

**Comment by mhvk** [comment]
Yes, I'd do it similarly. In principle, one could have a `replicate` or `copy` method (bit analogous to astropy `Time`), which allowed overrides for some arguments. It might have some common code with the pickle mechanism.

**Comment by theXYZT** [comment]
It would be useful to have a `copy()` method. The method I mentioned above requires knowing the input `format` and `**kwargs` a priori. What if I simply have some arbitrary instance of `baseband.base.base.StreamReaderBase`? What's the best way currently to copy such an object?

**Comment by theXYZT** [comment]
It also turns out that doing `fh2 = guppi.open(fh.fh_raw.name, ...)` does not work when `name` was a list of filenames, such as when passed to a SequentialFileReader.

**Comment by mhvk** [comment]
Best current way is to pickle and unpickle...  I vaguely recall the same protocol is used by the copy module. Maybe try `import copy; copy.[deep]copy(fh)`?
