### ISSUE TITLE
Baseband doesn't properly support file paths in all cases

### ISSUE THREAD

**Issue by theXYZT** [mhvk/baseband#465]
Using `pathlib` to store paths to files is not fully supported. Here's an example:

```
In [1]: import baseband

In [2]: from pathlib import Path

In [3]: fname = Path('fake.0.raw')

In [4]: baseband.open(fname)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-c398cf3df919> in <module>
----> 1 baseband.open(fname)

C:\ProgramData\Anaconda3\envs\main\lib\site-packages\baseband\io\__init__.py in open(name, mode, format, **kwargs)
    197             raise ValueError("cannot specify multiple formats for writing.")
    198
--> 199         info = file_info(name, format, **kwargs)
    200         if not info:
    201             raise ValueError("format of file could not be auto-determined")

C:\ProgramData\Anaconda3\envs\main\lib\site-packages\baseband\io\__init__.py in file_info(name, format, **kwargs)
    138         no_info = set()
    139         for format_ in format:
--> 140             info = file_info(name, format_, **kwargs)
    141             if info:
    142                 return info

C:\ProgramData\Anaconda3\envs\main\lib\site-packages\baseband\io\__init__.py in file_info(name, format, **kwargs)
    154     # from it (which may well work if VLBIStreamReaderBase is subclasses).
    155     if hasattr(module, 'info'):
--> 156         return module.info(name, **kwargs)
    157
    158     # Try just opening as stream and getting info.

C:\ProgramData\Anaconda3\envs\main\lib\site-packages\baseband\base\base.py in info(*args, **kwargs)
   1550         @functools.wraps(self.__call__)
   1551         def info(*args, **kwargs):
-> 1552             return self(*args, **kwargs)
   1553
   1554         if doc:

C:\ProgramData\Anaconda3\envs\main\lib\site-packages\baseband\base\base.py in __call__(self, name, **kwargs)
   1447         # rather in the info implementations.
   1448         file_info = self.get_file_info(name, **kwargs)
-> 1449         if not file_info or file_info.missing:
   1450             return file_info
   1451

AttributeError: 'ValueError' object has no attribute 'missing'

In [5]: baseband.open(str(fname))
Out[5]:
<GUPPIStreamReader name=fake.0.raw offset=0
    sample_rate=3125000.0 Hz, samples_per_frame=1024,
    sample_shape=SampleShape(npol=2, nchan=4), bps=8,
    start_time=1997-07-11T12:34:56.000>

In [6]: baseband.open([fname])
Out[6]:
<GUPPIStreamReader name=fake.0.raw offset=0
    sample_rate=3125000.0 Hz, samples_per_frame=1024,
    sample_shape=SampleShape(npol=2, nchan=4), bps=8,
    start_time=1997-07-11T12:34:56.000>

```

Converting the path to a string works. Additionally, placing the path object into a list works too. This explains why I never encountered this problem before as I have been mostly working with GUPPI data using multiple sequential files.

**Comment by mhvk** [comment]
Yes, it breaks in a test that assumes whatever is passed in can be indexed - https://github.com/mhvk/baseband/blob/0ff51ae13a80454d5df673532416bb2b4011c706/baseband/base/base.py#L1645-L1652

Should not be too hard to fix, need to think a bit more clearly about how one duck-types appropriately here.

**Comment by theXYZT** [comment]
So, if I understand correctly, there are three cases, we care about:

1. name is a path-like object
2. name is a sequence of path-like objects
3. everything else is unsupported

Why not try to `open` the file as is, if it fails, pass it on to the Sequencer. If it fails there, raise an error. That seems to be the best way to handle this while following EAFP.

The best way to duck-type a filename, is to simply open it!

**Comment by mhvk** [comment]
Yes, would be good, except that the file name can have '{' and '}' in it to indicate that it is a template...  Also, if opened for writing, this has the side effect that something gets created (with the code perhaps erroring later). Anyway, I'll think a bit about it - one way might actually to try putting the item in `Path`, and let that worry about it.

**Comment by mhvk** [comment]
See #467 for a fix. I think path templates would not actually work yet, but that's for a later PR.

**Comment by theXYZT** [comment]
Path objects probably shouldn't be used with templates involving placeholder variables since they aren't strings, so maybe we can safely assume they are always complete.
