### ISSUE TITLE
Inconsistent sample_shape between VDIF StreamReader and header?

### ISSUE THREAD

**Issue by theXYZT** [mhvk/baseband#471]
I was looking at the `sample.vdif` file used for testing here and I did the following:

```
In [45]: fh = baseband.open('sample.vdif')

In [46]: h = fh.header0

In [47]: fh.sample_shape
Out[47]: SampleShape(nthread=8)

In [48]: h.sample_shape
Out[48]: (1,)

In [49]: h
Out[49]:
<VDIFHeader3 invalid_data: False,
             legacy_mode: False,
             seconds: 14363767,
             _1_30_2: 0,
             ref_epoch: 28,
             frame_nr: 0,
             vdif_version: 1,
             lg2_nchan: 0,
             frame_length: 629,
             complex_data: False,
             bits_per_sample: 1,
             thread_id: 1,
             station_id: 65532,
             edv: 3,
             sampling_unit: True,
             sampling_rate: 16,
             sync_pattern: 0xacabfeed,
             loif_tuning: 859832320,
             _7_28_4: 15,
             dbe_unit: 2,
             if_nr: 0,
             subband: 1,
             sideband: True,
             major_rev: 1,
             minor_rev: 5,
             personality: 131>

```

It appears that `fh.sample_shape` and `fh.header0.sample_shape` don't agree with each other. Is this intended behavior?

**Comment by mhvk** [comment]
VDIF has the concept of threads (`thread_id` in the header), so the sample shape is the number of threads and the number of channels. See https://baseband.readthedocs.io/en/stable/vdif/index.html#file-structure. It is often a thing that makes the stream readers more difficult to generalize...

**Comment by theXYZT** [comment]
So, does every thread has it's own header?

**Comment by mhvk** [comment]
Indeed, every thread has its own header.

And, indeed, do not rely on just the header (for some Mark 5B headers, the time stamps are even missing the fractional seconds), but instead rely attributes of the stream reader proper (or `.info`, though for the stream readers that doesn't add much; it is mostly useful for the binary file readers).
