### ISSUE TITLE
Guaranteed Attributes/Methods for headers?

### ISSUE THREAD

**Issue by theXYZT** [mhvk/baseband#472]
I was looking at what the guaranteed attributes/methods are for a header object regardless of format. So when you call `baseband.open(...).header0`, what can you expect to always have as an attribute/method?

I opened a bunch of sample files from baseband/data and used `dir(header)` to find all attributes/methods (I ignore those starting with underscores) for headers from GUPPI, VDIF, DADA, Mark4, and Mark5B. I was surprised to find that some format headers are missing a few attributes that I think should be included.

I noticed that both Mark4 and Mark5B are missing a `sample_rate` attribute (I would love it if this could be added).

Just to be a bit formal, here is the output from counting the attributes via `collections.Counter` (where a count of 5 means it's common to all formats tested, and so on), and I have truncated the attributes with a count of 1 (since those are probably very format-specific and not worth guaranteeing):

```
{'complex_data': 5,
 'copy': 5,
 'frame_nbytes': 5,
 'fromfile': 5,
 'fromkeys': 5,
 'fromvalues': 5,
 'keys': 5,
 'mutable': 5,
 'nbytes': 5,
 'payload_nbytes': 5,
 'time': 5,
 'tofile': 5,
 'update': 5,
 'verify': 5,
 'bps': 4, # Missing: Mark5B
 'sample_shape': 4, # Missing: Mark5B
 'samples_per_frame': 4, # Missing: Mark5B
 'nchan': 3,
 'sample_rate': 3, # Missing: Mark4, Mark5B
 'get_time': 3,
 'invariant_pattern': 3,
 'invariants': 3,
 'set_time': 3,
 'words': 3,
 'clear': 2,
 'comments': 2,
 'get': 2,
 'items': 2,
 'offset': 2,
 'pop': 2,
 'popitem': 2,
 'setdefault': 2,
 'sideband': 2,
 'start_time': 2,
 'values': 2,
 'fraction': 2,
}
```

I feel like it would be worth having a list of guaranteed attributes and methods for all headers and I recommend the following: `{'bps', 'complex_data', 'copy', 'frame_nbytes', 'fromfile', 'fromkeys', 'fromvalues', 'keys', 'mutable', 'nbytes', 'payload_nbytes', 'time', 'tofile', 'update', 'verify', 'sample_shape', 'samples_per_frame', 'sample_rate'}`

**Comment by mhvk** [comment]
I think we can only discuss guaranteed attributes for a stream reader; e.g., the Mark 5 header simply does not have information about even the sample shape (nor does the file itself; it has to be passed in...). Indeed, this impossibility of having common information is why I wrote the `info` class.

**Comment by theXYZT** [comment]
I was confused by the existence of `VLBIHeaderBase` and thinking it was the intended "metadata container". Then, I was confused when I noticed that the headers of some formats don't inherit from it at all.

So, we should be using the `Info` class for all our metadata needs? That's fine then, I guess. We can close this issue because it was mainly about having a metadata container common to all formats and it seems `Info` is fulfilling this goal right now.

**Comment by mhvk** [comment]
Yes, `Info` is meant to be the general meta-data container. `VLBIHeaderBase` just contains methods specific to getting information out of bit-encoded headers, for searching headers, etc.
