### ISSUE TITLE
Documentation for encode_2bit_base swaps encodings 1 and 2

### ISSUE THREAD

**Issue by bmerry** [mhvk/baseband#521]
The documentation for basebase.base.encoding.encode_2bit_base says:
```
      ================= ======
      Input range       Output
      ================= ======
            value < -lv   0
      -lv < value <  0.   2
       0. < value <  lv   1
       lv < value         3
      ================= ======
```
Based on the implementation, the output column ought to be 0, 1, 2, 3 (so 1 and 2 are swapped).

**Comment by mhvk** [comment]
Darn, you are right, that is a bad copy from what mark4 and mark5b do.
