### ISSUE TITLE
Mark4 Reader does not operate correctly on BlueGene/Q

### ISSUE THREAD

**Issue by theXYZT** [mhvk/baseband#56]
Running `baseband.test()` on BGQ generates a test output that I have pasted here:
https://pastebin.com/raw/zeTMJaqP

It seems like the mark4 reader doesn't operate correctly in big-endian environments.

**Comment by theXYZT** [comment]
With #65 done, I think this issue can be closed.

**Comment by mhvk** [comment]
Indeed, thanks!
