### ISSUE TITLE
Mark5B reader gets confused at midnight?

### ISSUE THREAD

**Issue by theXYZT** [mhvk/baseband#82]
Hi,
I noticed this bug in the Crab data (Effelsberg Mark5B data). If an observation spans across two MJD dates (that is, when midnight is in the middle of the observation), the reader throws an error.

Here's some iPython output using a file, "ek036a_ef_no0006.m5a" which spans from `2015-10-18T23:51:35.000000000` to `2015-10-19T00:03:55.000078125` in ISO time.

The file is inexplicably unreadable past midnight. Here's some iPython output to illustrate that:

    In [34]: (fh.time0 + 504*u.s).isot
    Out[34]: '2015-10-18T23:59:59.000000000'

    In [35]: fh.seek(fh.time0 + 504*u.s)
    Out[35]: 16128000000

    In [36]: z = fh.read(32000000)

    In [37]: fh.seek(fh.time0 + 504*u.s)
    Out[37]: 16128000000

    In [38]: z = fh.read(32000001)
    ---------------------------------------------------------------------------
    AssertionError                            Traceback (most recent call last)
    <ipython-input-38-c3cf624c62ff> in <module>()
    ----> 1 z = fh.read(32000001)

    /mnt/raid-cita/rlin/packages/baseband/baseband/mark5b/base.pyc in read(self, count, fill_value, squeeze, out)
        229                 # Read relevant frame, reusing data array from previous frame.
        230                 self._read_frame()
    --> 231                 assert dt == (self._frame.seconds - self.header0.seconds)
        232                 assert frame_nr == self._frame['frame_nr']
        233

    AssertionError:

    In [39]: fh.time1.isot
    Out[39]: '2015-10-19T00:03:55.000078125'

As you can see, in the test I seek to 1 second before midnight and successfully read exactly 1 second of data (32 million samples). However, reading 32000000+1 samples leads to an error, because the file is somehow unreadable beyond midnight. The same is true for seeking well beyond midnight and attempting to read any number of samples.

The file is perfectly readable for all samples before midnight.

**Comment by mhvk** [comment]
OK, the problem is that the `assert` statement is not aware of days...
It should be
```
assert dt == (self._frame.seconds - self.header0.seconds +
              86400 * (self._frame.jday - self.header0.jday))
```

@cczhu - would you be able to make a fix with a test? (The alternative would be to directly compare times, but that is a more costly calculation.)

**Comment by cczhu** [comment]
Done!  See pull request.
