### ISSUE TITLE
Descriptive "whence" values for `.seek()`

### ISSUE THREAD

**Issue by theXYZT** [mhvk/baseband#92]
`.seek()` takes in an argument `whence` which can be either `0`, `1` or `2` to mean "from start", "from current" and "from end", respectively.

Can we change this to a string-based argument to be more obviously descriptive in the code and in general, good code design.

So, `whence='start'`, `whence='current'`, or `whence='end'`.
That would be much more readable.

**Comment by mhvk** [comment]
We could have those as alternates; in general, I tried to copy what a general python file handle does, so I'd be loath to change the possibility of having numbers.

**Comment by cczhu** [comment]
I'm happy to provide the option, but agree with @mhvk that the file seeker should also support whatever Python file handle defaults to.  PR #93 adds string input options to `whence`.

**Comment by mhvk** [comment]
fixed by #93
